#!/bin/bash

DZEN_FG="#909090"
DZEN_BG="#1F1F1F"
WIDTH=210
PARENTPOS=20
X=`expr $(xwininfo -root | sed -n 's|Width: \([0-9]*$\)|\1|p') - $WIDTH - $PARENTPOS`
Y=18
FONT="-*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*"
DZEN="dzen2 -l 6  -x $X -y $Y -w $WIDTH -fn $FONT -sa l -bg $DZEN_BG -fg $DZEN_FG -p"
EVENTS='onstart=uncollapse'

battery(){
 bat=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 | \
   sed -nre "s/.*(energy:|voltage:|capacity:|technology:|state:)(.*$)$/^p(12)\1^fg(#D0D0D0)\2^fg()/p")
 echo "$bat"
}

# if clicked again, kill the sub-bar
pid=`cat /tmp/dzenbar-batt-pid`
if [[ -z $pid ]]; then
  (echo "^fg(#D0D0D0)Battery Info^fg()"; echo "$(battery)") | \
  $DZEN -e $EVENTS & echo $! > /tmp/dzenbar-batt-pid
  exit 0
else
  kill -0 $pid 2>/dev/null
  if [[ $? == 1 ]]; then
    (echo "^fg(#D0D0D0)Battery Info^fg()"; echo "$(battery)") | \
    $DZEN -e $EVENTS & echo $! > /tmp/dzenbar-batt-pid
    exit 0
  fi
fi

kill -9 $pid


