#!/bin/bash
title() {
    unread=$(ls -1 ~/Mail/ETH/INBOX/new | wc -l)
    echo -n "^p(7)^fg(#E0E0E0)Unread Mails ($unread)^fg()"
}
newmails() {
    entered=0
    for f in ~/Mail/ETH/INBOX/new/*
    do
      if test $entered -eq 1 ; then
        echo `printf "%-64s" "-" | sed 's/ /-/g'` 
      fi
      ~/.i3/clickables/parse_mails $f
      entered=1
    done
}

DZEN_FG="#909090"
DZEN_BG="#1F1F1F"
WIDTH=410
PARENTPOS=3
X=`expr $(xwininfo -root | sed -n 's|Width: \([0-9]*$\)|\1|p') - $WIDTH - $PARENTPOS`
Y=18
FONT="-*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*"
DZEN="dzen2 -l 11  -x $X -y $Y -w $WIDTH -fn $FONT -sa l -bg $DZEN_BG -fg $DZEN_FG -p"
EVENTS='onstart=uncollapse'

pid=`cat /tmp/dzenbar-email-pid`
if [[ -z $pid ]]; then
  (echo "$(title)"; echo "$(newmails)"; sleep 3) | $DZEN -e $EVENTS & echo $! > /tmp/dzenbar-email-pid
  exit 0
else
  kill -0 $pid 2>/dev/null
  if [[ $? == 1 ]]; then
    (echo "$(title)"; echo "$(newmails)"; sleep 3) | $DZEN -e $EVENTS & echo $! > /tmp/dzenbar-email-pid
    exit 0
  fi
fi

kill -9 $pid


