#!/usr/bin/env python
import sys
import email
import email.header
import datetime
import time

if len(sys.argv) != 2:
  sys.exit(-1)

with open(sys.argv[1]) as f:
  mail = email.message_from_file(f)

dh = email.header.decode_header(mail.get('subject'))
subj_str = ''.join([ unicode(t[0], t[1] or 'UTF-8') for t in dh ])

str_list = []
str_list.append("From: " + mail.get('from'))
str_list.append("Subj: " + subj_str)

date_str = mail.get('date')
date = None
if date_str:
    date_tuple = email.utils.parsedate_tz(date_str)
    if date_tuple:
        date = datetime.datetime.fromtimestamp(email.utils.mktime_tz(date_tuple))
if date:
  str_list.append(date.strftime("Time: %b %a %d - %H:%M ") + time.strftime("%Z"))

print(u"\n".join(str_list).encode('utf-8').strip())
