#!/bin/bash

DZEN_FG="#909090"
DZEN_BG="#1F1F1F"
WIDTH=275
PARENTPOS=80
X=`expr $(xwininfo -root | sed -n 's|Width: \([0-9]*$\)|\1|p') - $WIDTH - $PARENTPOS`
Y=18
FONT="-*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*"
DZEN="dzen2 -l 20  -x $X -y $Y -w $WIDTH -fn $FONT -sa l -bg $DZEN_BG -fg $DZEN_FG -p"
EVENTS='onstart=uncollapse'

pid=`cat /tmp/dzenbar-sysinfo-pid`
if [[ -z $pid ]]; then
  conky -c ~/.i3/clickables/conky_sysinfo | $DZEN -e $EVENTS & echo $! > /tmp/dzenbar-sysinfo-pid
  exit 0
else
  kill -0 $pid 2>/dev/null
  if [[ $? == 1 ]]; then
    conky -c ~/.i3/clickables/conky_sysinfo | $DZEN -e $EVENTS & echo $! > /tmp/dzenbar-sysinfo-pid
    exit 0
  fi
fi

kill -9 $pid


