#!/bin/bash

# change color of the icons in the colorizable folder
color="#008080"
color2="#00aaaa"
if hash convert 2>/dev/null; then
  for f in $@
  do
    echo "Converting "$f
    if [[ `identify -format %A $f` == "True" ]]; then
      convert \( $f -alpha extract \) -background $color -alpha shape ${f##*/}
    else
      convert $f -fuzz 5% -fill $color -opaque white ${f##*/}
    fi
    if [[ $f == *"square_unsel"* ]]; then
      # This should use unselected color
      convert square_unsel.png -gamma 0.5 square_unsel.png
    fi
  done
else
  echo "Please install convert"
fi

