source $HOME/.config/nvim/startup/plugins/airline.vim
source $HOME/.config/nvim/startup/plugins/ale.vim
source $HOME/.config/nvim/startup/plugins/autopairs.vim
source $HOME/.config/nvim/startup/plugins/clever-f.vim
source $HOME/.config/nvim/startup/plugins/cpp_highlight.vim
source $HOME/.config/nvim/startup/plugins/deoplete.vim
source $HOME/.config/nvim/startup/plugins/easyescape.vim
source $HOME/.config/nvim/startup/plugins/fzf.vim
source $HOME/.config/nvim/startup/plugins/gutentags.vim
source $HOME/.config/nvim/startup/plugins/highlightedyank.vim
source $HOME/.config/nvim/startup/plugins/language-client.vim
source $HOME/.config/nvim/startup/plugins/local_vimrc.vim
source $HOME/.config/nvim/startup/plugins/mundo.vim
source $HOME/.config/nvim/startup/plugins/neodark.vim
source $HOME/.config/nvim/startup/plugins/neoformat.vim
source $HOME/.config/nvim/startup/plugins/operator_replace.vim
source $HOME/.config/nvim/startup/plugins/rooter.vim
source $HOME/.config/nvim/startup/plugins/sbd.vim
source $HOME/.config/nvim/startup/plugins/signify.vim
source $HOME/.config/nvim/startup/plugins/signjk.vim
source $HOME/.config/nvim/startup/plugins/startify.vim
source $HOME/.config/nvim/startup/plugins/supersearch.vim
source $HOME/.config/nvim/startup/plugins/tagbar.vim
source $HOME/.config/nvim/startup/plugins/tcomment.vim
source $HOME/.config/nvim/startup/plugins/textobj-parameter.vim
source $HOME/.config/nvim/startup/plugins/vimtex.vim
source $HOME/.config/nvim/startup/plugins/windowswap.vim
source $HOME/.config/nvim/startup/plugins/list-toggle.vim
