#!/bin/sh
# Start email client on the background
# offlineimap -l ~/.offlineimap/log &

# Set color, xterm and other resources
xrdb ~/.Xresources &

# Customize peripherals
# xinput --set-prop 'Razer  Razer Abyssus' 'Device Accel Constant Deceleration' 2 &
setxkbmap -option caps:escape &
setxkbmap -option escape:caps &

# Start compositor
compton &

# Start notification daemon
dunst &

# Hide mouse
unclutter &

# Dimm lights according to time of day
redshift &

# Start music player daemon
# mpd &

# Refresh X
xrefresh &

# Draw status bar
/home/fede/.i3/dzen_conky

# Set background image
feh  --bg-scale '/home/fede/.i3/wall.jpg' &

# Set monitors on the correct side.
xrandr --output DVI-D-0 --auto --right-of DVI-I-1

# Have fun :)
exit 0
