#!/bin/sh
#
# Wait for program coming up, depends on xdotool and notify-send
#
wait_for_program () {
  n=0
  while true
  do
    # PID of last background command
    if xdotool search --onlyvisible --pid $! 2>/dev/null; then
      break
    else
      if [ $n -eq 90 ]; then
        notify-send -u critical "Error during start"
        break
      else
        n=`expr $n + 1`
        sleep 0.5
      fi
    fi
  done
}

# Set color, xterm and other resources
xrdb ~/.Xresources &

# Customize peripherals
# xinput --set-prop 'Razer  Razer Abyssus' 'Device Accel Constant Deceleration' 2 &
setxkbmap -option caps:escape &

# Start compositor
compton &

# Set background image
feh  --bg-scale '/home/fede/.i3/wall.jpg' &
#exec sh ~/.fehbg

# Start notification daemon
dunst &

# Hide mouse
unclutter &

# Dimm lights according to time of day
redshift &

# Start music player daemon
mpd &

# Fire up a terminal
# xterm &
# wait_for_program

# Refresh X
# xrefresh &
# Draw status bar
~/.i3/dzen_conky

# Have fun :)
exit 0
