#!/bin/zsh
#
# check only the inbox folder using quick-mode
#

notify-send --expire-time=100 "Offlineimap: Fastsync mail ..."
out_imap=$(/usr/bin/offlineimap -qof INBOX 2> /dev/null)
to_notif=$(echo $out_imap| tail -n 1 | sed 's/ \** //' | sed 's/ Sync/Sync/')
echo $to_notif
notify-send --expire-time=100 $to_notif
