#!/bin/zsh
#
# Sync IMAP
#

notify-send --expire-time=200 "Offlineimap: Syncing ALL mail ..."
out_imap=$(/usr/bin/offlineimap -o INBOX 2> /dev/null)
to_notif=$(echo $out_imap| tail -n 1 | sed 's/ \** //' | sed 's/ Sync/Sync/')
echo $to_notif
notify-send --expire-time=100 $to_notif
