#!/bin/zsh
#
# check only the inbox folder using quick-mode
#

notify-send --expire-time=100 "Offlineimap" "Checking email"
out_imap=`{ offlineimap -o -f INBOX > /dev/null } 2>&1`
to_notif=$(echo $out_imap| tail -n +7 | sed 's/ \*\*\* //' | sed 's/ Sync/Sync/')
echo $to_notif
notify-send "Offlineimap" $to_notif
