#!/bin/bash
# ------------------------------------------------------
# Dzen settings & Variables
# -------------------------
DZEN_FG="#A0A0A0"
DZEN_BG="#1f1f1f"
HEIGHT=12
WIDTH=1300
X=2575
Y=2
FONT="-*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-*"
EVENTS="-e ''"
DZEN_TITLE="dzen_topbar"
DZEN="dzen2 -x $X -y $Y -w $WIDTH -h $HEIGHT -fn $FONT -ta right -bg $DZEN_BG -fg $DZEN_FG
-title-name $DZEN_TITLE -slave-name $DZEN_TITLE -p"

conky -c ~/.i3/conky_scripts/conkyrc_top | $DZEN & echo $! > /tmp/dzenbar-pid
