#!/bin/bash

function hide {
    xdotool windowunmap $wid
}

function show {
    xdotool windowmap $wid
}

function toggle {
    is_mapped=$(xdotool search --maxdepth 1 --onlyvisible --pid $pid)
    if [[ -z $is_mapped ]]; then
      show
    else
      hide
    fi
}

pid=`cat /tmp/dzenbar-pid`
if [[ -z $pid ]]; then
  exec $(pwd)/dzen_conky
  exit 0
else
  kill -0 $pid 2>/dev/null
  if [[ $? == 1 ]]; then
    exec $(pwd)/dzen_conky
    exit 0
  fi
fi

wid=$(xdotool search --maxdepth 1 --pid $pid 2> /dev/null)
if [[ -z $wid ]]; then
  echo "Something is wrong"
  exit 1
else
  toggle 2> /dev/null
fi

